### ISSUE TITLE
portable to Windows?

### ISSUE THREAD

**Issue by ZekunYin** [cjw85/fastx#1]
fastx seems not portable to windows platform (anaconda pip) currently.
Is there a fix?
Best,
Zekun

**Comment by cjw85** [comment]
This code was made solely for the purposes fo demonstrating a fast python fastq parser that works under PyPy as an entry into https://github.com/lh3/biofast. I'm unlikely to have spare time to create windows packages for the code.

**Comment by ZekunYin** [comment]
Thanks for the response. kseq seems not portable to windows as well. I will test other packages.
Best, Zekun
