### ISSUE TITLE
No module named '_fastx'

### ISSUE THREAD

**Issue by ZekunYin** [cjw85/fastx#3]
Hi,
The fastx pypi package seems could not work properly on both ubuntu18.04 and centos 8.1.
This is the error message:
```bash
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yzk/.local/lib/python3.6/site-packages/fastx/__init__.py", line 1, in <module>
    import _fastx
ModuleNotFoundError: No module named '_fastx'
```
But the installation using the source code from this repo works well on my test platform.
Could you please update the pypi package?

Best

**Comment by cjw85** [comment]
Hi @ZekunYin,

Do you have a specific reason for using `fastx`? As noted in the README it is not intended for general use. For that I would use the functionality available in pysam.

**Comment by cjw85** [comment]
The pypi package has been set to require CFFI during the install process.

**Comment by ZekunYin** [comment]
Thanks for your suggestion and update. I'd like to use fastx for its efficiency. I will try other general-purpose libraries as well.
Thanks again.
Best,
Zekun
